version: "3"
services:
  mlops:
    image: mlops-image
    container_name: mlops
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu,compute,utility,graphics,display]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/app/mlops
    # -RenderOffScreen
    command: tail -F anything
